--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version: P.68d
--  \   \         Application: netgen
--  /   /         Filename: .vhd
-- /___/   /\     Timestamp: Wed Jan 22 15:58:35 2020
-- \   \  /  \ 
--  \___\/\___\
--             
-- Command	: -intstyle ise -ar Structure -tm mu0_mem -w -dir netgen/synthesis -ofmt vhdl -sim mu0_mem.ngc mu0_mem_synthesis.vhd 
-- Device	: xc7a100t-3-csg324
-- Input file	: mu0_mem.ngc
-- Output file	: C:\Users\hp\Desktop\Projet VHDL\microprocesseur\netgen\synthesis\mu0_mem_synthesis.vhd
-- # of Entities	: 1
-- Design Name	: mu0_mem
-- Xilinx	: C:\Xilinx\14.6\ISE_DS\ISE\
--             
-- Purpose:    
--     This VHDL netlist is a verification model and uses simulation 
--     primitives which may not represent the true implementation of the 
--     device, however the netlist is functionally correct and should not 
--     be modified. This file cannot be synthesized and should only be used 
--     with supported simulation tools.
--             
-- Reference:  
--     Command Line Tools User Guide, Chapter 23
--     Synthesis and Simulation Design Guide, Chapter 6
--             
--------------------------------------------------------------------------------

